name: Questionable Hacks
description: by Kevin Yeh
author: kevinyeah@utexas.edu

url: http://kyeh.me

markdown: rdiscount
permalink: pretty

collections:
  projects:
    output: false
  films:
    output: true
    permalink: /:collection/:title/